tap "aws/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "rtau/rancher-cli"
# Automatic configure script builder
brew "autoconf"
# Tool for generating GNU Standards-compliant Makefiles
brew "automake"
# Extendable version manager with support for Ruby, Node.js, Erlang & more
brew "asdf"
# Advanced SSH config - Regex, aliases, gateways, includes and dynamic hosts
brew "assh"
# Official Amazon AWS command-line interface
brew "awscli"
# Parser generator
brew "bison"
# Library for manipulating PNG images
brew "libpng"
# Software library to render fonts
brew "freetype"
# GNU internationalization (i18n) and localization (l10n) library
brew "gettext"
# Enables you to reproduce the CircleCI environment locally
brew "circleci"
# Dependency Manager for PHP
brew "composer"
# Load/unload environment variables based on $PWD
brew "direnv"
# Distributed search & analytics engine
brew "elasticsearch", restart_service: true
# Manage compile and link flags for libraries
brew "pkg-config"
# Generate introspection data for GObject libraries
brew "gobject-introspection"
# C/C++ and Java libraries for Unicode and globalization
brew "icu4c"
# Image manipulation library
brew "jpeg"
# Subtitle renderer for the ASS/SSA subtitle format
brew "libass"
# Blu-Ray disc playback library for media players like VLC
brew "libbluray"
# Play, record, convert, and stream audio and video
brew "ffmpeg"
# User-friendly command-line shell for UNIX-like operating systems
brew "fish"
# Lossy LZW compression, reduces GIF file sizes by 30-50%
brew "giflossy"
# Enable transparent encryption/decryption of files in a git repo
brew "git-crypt"
# Simple jira command-line client in Go
brew "go-jira"
# Graph visualization software from AT&T and Bell Labs
brew "graphviz"
# Improved top (interactive process viewer)
brew "htop"
# Add GitHub support to git on the command-line
brew "hub"
# Tools and libraries to manipulate images in many formats
brew "imagemagick"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Network authentication protocol
brew "krb5"
# Sophisticated file transfer program
brew "lftp"
# BSD-style licensed readline alternative
brew "libedit"
# Conversion library
brew "libiconv"
# Postgres C API library
brew "libpq"
# Library to render SVG files using Cairo
brew "librsvg"
# GNOME XML library
brew "libxml2"
# C library for reading, creating, and modifying zip archives
brew "libzip"
# Keep your Mac's application settings in sync
brew "mackup"
# Open source relational database management system
brew "mysql", restart_service: true
# NCurses Disk Usage
brew "ncdu"
# Manage multiple NodeJS versions
brew "nodenv"
# Libraries for security-enabled client and server applications
brew "nss"
# Tool to automatically fix PHP coding standards issues
brew "php-cs-fixer"
# General-purpose scripting language
brew "php@7.2"
# General-purpose scripting language
brew "php@7.3"
# Object-relational database system
brew "postgresql", restart_service: true
# Monitor data's progress through a pipe
brew "pv"
# Generate C-based recognizers from regular expressions
brew "re2c"
# Reattach process (e.g., tmux) to background
brew "reattach-to-user-namespace"
# Utility that provides fast incremental file transfer
brew "rsync"
# Powerful, clean, object-oriented scripting language
brew "ruby"
# Fast and accurate code counter with complexity and COCOMO estimates
brew "scc"
# Send macOS User Notifications from the command-line
brew "terminal-notifier"
# Text interface for Git repositories
brew "tig"
# Terminal multiplexer
brew "tmux"
# Manage complex tmux sessions easily
brew "tmuxinator"
# Executes a program periodically, showing output fullscreen
brew "watch"
# Internet file retriever
brew "wget"
# Command-line interface for WordPress
brew "wp-cli"
# Download YouTube videos from the command-line
brew "youtube-dl"
# Process YAML documents from the CLI
brew "yq"
# General-purpose lossless data-compression library
brew "zlib"
# The Rancher CLI 0.6.x is a unified tool to manage your Rancher v1.6 server
brew "rtau/rancher-cli/rancher-cli@0.6"
cask "1password-cli"
cask "adoptopenjdk8"
cask "android-platform-tools"
cask "android-studio"
cask "aws-vault"
cask "barrier"
cask "calibre"
cask "cyberduck"
cask "dbeaver-community"
cask "discord"
cask "docker"
cask "firefox"
cask "inkscape"
cask "keka"
cask "kindle"
cask "libreoffice"
cask "magicprefs"
cask "react-native-debugger"
cask "send-to-kindle"
cask "skype"
cask "spotify"
cask "transmission"
cask "use-engine"
cask "visual-studio-code"
cask "vlc"
